// ===== Acervo do Barrifórnia — dados reais extraídos do arquivo da família =====
// 42 edições, 763 músicas. Campeãs marcadas com base nas etiquetas do acervo.
const edicoes = [
  { numero: 1, ano: 1982, musicas: [
    { titulo: "Mentira... que coisa feia", grupo: "Arriba Véio" },
    { titulo: "Chega Mais", grupo: "Ala Jovem" },
    { titulo: "Oração à Tia Renata", grupo: "Arriba Véio" },
    { titulo: "Bolhinha de Ermão", grupo: "Arriba Véio" },
    { titulo: "Pega na Mentira", grupo: "Ala Jovem Masc" },
    { titulo: "Traição", grupo: "Ala Jovem Fem" },
    { titulo: "Veraneio", grupo: "Turma da Hora Certa", campea: true },
    { titulo: "Babás", grupo: "Ala Jovem Fem" },
    { titulo: "Adeus Katita", grupo: "Arriba Véio" },
    { titulo: "Nossas Matas São Mais Verdes", grupo: "Arriba Véio" },
    { titulo: "Disparada", grupo: "Ala Jovem" },
    { titulo: "Homenagem à Véia Englert’s", grupo: "Arriba Véio" },
    { titulo: "A Mesma Praia", grupo: "Ala Jovem" },
    { titulo: "O Petróleo é Nosso", grupo: "Arriba Véio" },
    { titulo: "Tragédia", grupo: "Ala Jovem Fem" },
    { titulo: "Esse Ano", grupo: "Ala Jovem Masc" },
    { titulo: "Carneirinho de Melão", grupo: "Arriba Véio" },
    { titulo: "Tarde a Sestear", grupo: "Ala Jovem" },
    { titulo: "Mulher Maravilha", grupo: "Arriba Véio" },
    { titulo: "Trova", grupo: "Ala Jovem Masc" },
    { titulo: "Praia Boa", grupo: "Turma da Hora Certa" },
    { titulo: "Caipira Virou", grupo: "Arriba Véio" },
    { titulo: "Eu Sou ou Não Sou", grupo: "Arriba Véio" },
  ] },
  { numero: 2, ano: 1983, musicas: [
    { titulo: "Sasso Levantador", grupo: "Arriba Véio" },
    { titulo: "Oração à Praia", grupo: "Grupo das 11 Horas" },
    { titulo: "Saudades do Martin", grupo: "Turma da Hora Certa" },
    { titulo: "Vôlei", grupo: "Grupo dos Náufragos" },
    { titulo: "Reencontro", grupo: "As Luluzinhas" },
    { titulo: "Canção para Ushi", grupo: "Arriba Véio" },
    { titulo: "Arraia", grupo: "" },
    { titulo: "Primas Não", grupo: "Grupo Chico Bento" },
    { titulo: "Tempos Mudados", grupo: "Grupo dos Náufragos" },
    { titulo: "Sonho em Dezembro", grupo: "Turma da Hora Certa" },
    { titulo: "Burro ao Cubo Menos 1", grupo: "Grupo Chima" },
    { titulo: "Alles Blau", grupo: "Luluzinhas" },
    { titulo: "Praia Véia", grupo: "Grupo das Onze Horas" },
    { titulo: "Mar, Picolé e Caipira", grupo: "Turma da Hora Certa" },
    { titulo: "Canção de Protesto na Praia", grupo: "Arriba Véio", campea: true },
    { titulo: "Música do Quatschi", grupo: "Grupo dos Náufragos" },
    { titulo: "A Verdade que Dói", grupo: "Ala Jovem Misto" },
    { titulo: "Barro Preto", grupo: "Arriba Véio" },
    { titulo: "A Antártida é Boa", grupo: "Grupo das Onze Horas" },
    { titulo: "Pé na Cova", grupo: "Grupo Chico Bento" },
    { titulo: "Barro Preto", grupo: "Grupo dos Náufragos" },
    { titulo: "Eleições", grupo: "As Luluzinhas" },
    { titulo: "Qual Praia que tem California", grupo: "Turma da Hora Certa" },
    { titulo: "Kombi", grupo: "Grupo das Onze Horas" },
    { titulo: "O que Vale é o Sonho", grupo: "Arriba Véio" },
    { titulo: "Música da Tia Heca", grupo: "" },
  ] },
  { numero: 3, ano: 1984, musicas: [
    { titulo: "Resposta", grupo: "Ala Jovem Fem" },
    { titulo: "Oma", grupo: "Micuins" },
    { titulo: "Zero Hora", grupo: "Ala Jovem Masc" },
    { titulo: "Dorminhoco", grupo: "Arriba Véio" },
    { titulo: "Familia", grupo: "Grupo Tchê" },
    { titulo: "Gente e Coisas", grupo: "Grupo Tchê" },
    { titulo: "Dona Eloá", grupo: "Equipiá" },
    { titulo: "Vai Vir Verão", grupo: "Ala Jovem Masc" },
    { titulo: "Barro Preto Azul", grupo: "Os Descontrolados" },
    { titulo: "Passeio pra Cidreira", grupo: "Equipiá" },
    { titulo: "Idos de 40", grupo: "Los Dos" },
    { titulo: "É um crime", grupo: "Ala Jovem Masc" },
    { titulo: "Apareça e Confira", grupo: "Turma da Hora Certa" },
    { titulo: "Barro Preto", grupo: "Equipiá" },
    { titulo: "Aids do Kaitis", grupo: "Arriba Véio" },
    { titulo: "Dominó", grupo: "Arriba Véio" },
    { titulo: "Beleza Pura", grupo: "Ala Jovem" },
    { titulo: "Astro da Estrela", grupo: "Ala Jovem" },
    { titulo: "Opa", grupo: "Ala Jovem Fem", campea: true },
    { titulo: "Renascer", grupo: "Arriba Véio" },
    { titulo: "Nordestão", grupo: "Grupo Tchê" },
    { titulo: "Chorinho Chorão", grupo: "Bissextos" },
    { titulo: "Sátira", grupo: "Ala Jovem Fem" },
    { titulo: "Barro Preto Capital", grupo: "Bissextos" },
    { titulo: "Pout Pourri", grupo: "Arriba Véio" },
    { titulo: "Réplica", grupo: "Arriba Véio" },
    { titulo: "Qual é a graça?", grupo: "Turma da Hora Certa" },
    { titulo: "Barro Preto", grupo: "Grupo Tchê" },
    { titulo: "Sem Querer", grupo: "Ala Jovem Masc" },
    { titulo: "Jogo Mentira", grupo: "Grupo Tchê" },
    { titulo: "O que é BomBacha e Bota", grupo: "Ala Jovem Masc" },
    { titulo: "Barro Preto das Famílias", grupo: "Bissextos" },
    { titulo: "Odisseia de Los Chilenos", grupo: "Os Chilenos" },
    { titulo: "Tchê", grupo: "Grupo Englert" },
    { titulo: "Família Tri Legal", grupo: "Ala Jovem" },
  ] },
  { numero: 4, ano: 1985, musicas: [
    { titulo: "Oma Punk", grupo: "Arriba Véio" },
    { titulo: "Amigos", grupo: "Micuins" },
    { titulo: "Descendentes", grupo: "Grupo Tchê" },
    { titulo: "O Salvador", grupo: "Turma da Hora Certa" },
    { titulo: "Nosso Veraneio", grupo: "Moranguinhos Silvestres" },
    { titulo: "Sucessão", grupo: "" },
    { titulo: "Die Elefant", grupo: "Moranguinhos Silvestres" },
    { titulo: "Vamos Embora", grupo: "Grupo Tchê" },
    { titulo: "Barrifórnia", grupo: "Turma da Hora Certa" },
    { titulo: "Isso é Bom", grupo: "Luluzinhas" },
    { titulo: "Classe A e B", grupo: "Arriba Véio" },
    { titulo: "Arriba Véio", grupo: "Moranguinhos Silvestres" },
    { titulo: "Paz dos Livres", grupo: "Grupo Tchê", campea: true },
    { titulo: "Superfantástico", grupo: "Micuins" },
    { titulo: "Festa de Família", grupo: "Turma da Hora Certa" },
    { titulo: "Nós", grupo: "Arriba Véio" },
    { titulo: "Remembranças", grupo: "Luluzinhas" },
    { titulo: "Schwartze Baden", grupo: "Moranguinhos Silvestres" },
    { titulo: "Oma Helga", grupo: "Grupo Tchê" },
    { titulo: "Barro Preto 2025", grupo: "Turma da Hora Certa" },
    { titulo: "Uma Prima no Mar", grupo: "Arriba Véio" },
    { titulo: "Lenta e Calma", grupo: "" },
    { titulo: "Homenagem à Canção", grupo: "Grupo Tchê" },
    { titulo: "Linda Praia", grupo: "Turma da Hora Certa" },
    { titulo: "Visão do Futuro", grupo: "Tio Jorge" },
    { titulo: "Sol de Verão", grupo: "Luluzinhas com 1 Morango" },
    { titulo: "Saudades do Pepão", grupo: "Turma da Hora Certa" },
    { titulo: "Volotcha", grupo: "Grupo Tchê" },
    { titulo: "Que Será Que Será", grupo: "Arriba Véio" },
    { titulo: "Pegando Jacaré", grupo: "Moranguinhos Silvestres" },
    { titulo: "Neuroses de uma família", grupo: "Arriba Véio" },
  ] },
  { numero: 5, ano: 1986, musicas: [
    { titulo: "Ano Novo", grupo: "Micuins" },
    { titulo: "Suou Malhou", grupo: "Banda da Panela" },
    { titulo: "Oma Érika", grupo: "Taranativista" },
    { titulo: "O Que Fazer? O Que Fazer?", grupo: "Arriba Véio" },
    { titulo: "Apocalipse", grupo: "Luluzinhas" },
    { titulo: "A Lenda o Índio Velox", grupo: "Turma da Hora Certa" },
    { titulo: "Paraíso", grupo: "Pra Lá do Valão" },
    { titulo: "Barro Preto", grupo: "Micuins" },
    { titulo: "Os Dois Lados do Valão", grupo: "Luluzinhas" },
    { titulo: "Marido Bom", grupo: "Arriba Véio" },
    { titulo: "Como é Bom", grupo: "Nós Dois" },
    { titulo: "Pode dar Bode", grupo: "Moranguinhos Silvestres" },
    { titulo: "Meinha Lou", grupo: "Taranativista" },
    { titulo: "Dia do Opapa", grupo: "Taranativista" },
    { titulo: "Olha o Puxa-Puxa", grupo: "Moranguinhos Silvestres", campea: true },
    { titulo: "Sem Dosa é Dose", grupo: "Baixo Astral: Tia Heca e seu violão desafinado" },
    { titulo: "Cordão dos Perús", grupo: "Arriba Véio" },
    { titulo: "Fio Dental", grupo: "Moranguinhos Silvestres" },
    { titulo: "Rei do Veraneio", grupo: "Melancias Campestres" },
    { titulo: "Lua de Mel", grupo: "creio que não foi apresentada" },
    { titulo: "Mim Quer Voltar", grupo: "Taranativista" },
    { titulo: "Sonho", grupo: "Taranativista" },
    { titulo: "Adivinha Quem É", grupo: "Moranguinhos Não Radicais" },
    { titulo: "Genesis", grupo: "creio que não foi apresentada" },
    { titulo: "A Volta do Baião", grupo: "Arriba Véio" },
    { titulo: "Bugiu da Praia", grupo: "Taranativista" },
  ] },
  { numero: 6, ano: 1987, musicas: [
    { titulo: "Frustração", grupo: "Arriba Véio" },
    { titulo: "Praia Bonita", grupo: "Micuins" },
    { titulo: "Casarão", grupo: "Bissextos" },
    { titulo: "Mais", grupo: "Moranguinhos Silvestres" },
    { titulo: "Barro Preto", grupo: "Micuins" },
    { titulo: "Inverno na Serra ou Apanhado Geral do Veraneio 87", grupo: "Arriba Véio", campea: true },
    { titulo: "Nosso Festival", grupo: "Taranativista" },
    { titulo: "O Lugar", grupo: "Salvem as Baleias" },
    { titulo: "Um Incomoda Muita Gente", grupo: "Moranguinhos Silvestres" },
    { titulo: "A Melhor Praia da América", grupo: "Micuins e Taranativista" },
    { titulo: "Opa o que tu fez?", grupo: "Taranativista" },
    { titulo: "Super Heca", grupo: "Arriba Véio" },
    { titulo: "É Pau", grupo: "Moranguinhos Silvestres" },
    { titulo: "Tri Feliz", grupo: "Bissextos" },
    { titulo: "Bigamia", grupo: "Turma da Hora Certa" },
    { titulo: "Canto de Boas Vindas ao Manoel", grupo: "Taranativista" },
    { titulo: "O Que Eles Tem na Cabeça", grupo: "Salvem as Baleias" },
    { titulo: "Pedalando para Cidreira", grupo: "Arriba Véio" },
    { titulo: "Calhancleta", grupo: "Bissestos" },
    { titulo: "Ai, Perús", grupo: "Moranguinhos Silvestres" },
    { titulo: "Canção Para Você Distante", grupo: "Taranativista" },
    { titulo: "O Importante é Competir", grupo: "Arriba Véio" },
    { titulo: "Perú Marambá", grupo: "Moranguinhos Silvestres" },
  ] },
  { numero: 7, ano: 1988, musicas: [
    { titulo: "Muito Velho pra Muito Pouco Lugar", grupo: "Bichos de Pé" },
    { titulo: "Pout-pourri das casas", grupo: "Arriba Véio" },
    { titulo: "Viva o puxa-puxa", grupo: "Micuins" },
    { titulo: "Olha o chupa-chupa", grupo: "Bichos de Pé" },
    { titulo: "Adivinhe se Puder", grupo: "Arriba Véio" },
    { titulo: "Homenagem", grupo: "Evacuação Precoce" },
    { titulo: "Colorado Pé Furado", grupo: "Bichos de Pé" },
    { titulo: "Louco Amor", grupo: "Arriba Véio" },
    { titulo: "I Am Teenager", grupo: "Evacuação Precoce" },
    { titulo: "Amigo Companheiro", grupo: "Micuins" },
    { titulo: "Panela de Pressão", grupo: "Bichos de Pé" },
    { titulo: "Carinhoso", grupo: "Evacuação Precoce" },
    { titulo: "Barro Preto Ano 16", grupo: "Arriba Véio" },
    { titulo: "Caça ao Índio Velox", grupo: "Micuins" },
    { titulo: "Desquite", grupo: "Bichos de Pé" },
    { titulo: "Do Canal", grupo: "Evacuação Precoce" },
    { titulo: "Xingando o Xuri", grupo: "Arriba Véio", campea: true },
    { titulo: "Museu de Cera", grupo: "Bichos de Pé" },
  ] },
  { numero: 8, ano: 1989, musicas: [
    { titulo: "Tangos e Tragédias", grupo: "Ali Bebeu e Seus Quatro Beduínos" },
    { titulo: "Os Piolhinhos", grupo: "Siris" },
    { titulo: "Bicho É", grupo: "Ali Bebeu e Seus Quatro Beduínos" },
    { titulo: "A Praga", grupo: "Arriba Véio" },
    { titulo: "Rock dos Perus", grupo: "Ex-Perus" },
    { titulo: "Fim Triste", grupo: "Bissestos" },
    { titulo: "Ferro e Aço", grupo: "Ali Bebeu e Seus Quatro Beduínos" },
    { titulo: "Fertilidade", grupo: "Luluzinhas" },
    { titulo: "Que Primo!", grupo: "Micuins" },
    { titulo: "O Tio Que Eu Quero Ter", grupo: "Bissestos" },
    { titulo: "Praia de Parentes", grupo: "Luluzinhas" },
    { titulo: "Padrinhos de Praia", grupo: "Micuins" },
    { titulo: "Onibus Negreiro ou Escravidão na Praia", grupo: "Arriba Véio" },
    { titulo: "Meu Afilhado Cresceu", grupo: "" },
    { titulo: "Um Dia no Futuro", grupo: "Ali Bebeu e Seus Quatro Beduínos" },
    { titulo: "Vem Com a Gente Veranear Nesta Praia Tri-legal", grupo: "Micuins" },
    { titulo: "O Cravo", grupo: "Moranguinhos com Chantilly" },
    { titulo: "Instituto Nacional de Garotas Exuberantes", grupo: "Los Cucarachas" },
    { titulo: "Compondo na Chuva", grupo: "Ali Bebeu e Seus Quatro Beduínos" },
    { titulo: "Jurado Never", grupo: "Turma da Hora Certa" },
    { titulo: "Saudades dos 18", grupo: "" },
    { titulo: "Ernestina", grupo: "Ali Bebeu e Seus Quatro Beduínos" },
    { titulo: "Cacaricando", grupo: "Moranguinhos com Chantilly" },
    { titulo: "Churrasco prá Alemão", grupo: "Arriba Véio", campea: true },
    { titulo: "Ditados do Mar", grupo: "Ali Bebeu e Seus Quatro Beduínos" },
    { titulo: "Drama Pelancólico", grupo: "Moranguinhos Silvestres" },
  ] },
  { numero: 9, ano: 1990, musicas: [
    { titulo: "Não Deixem a Barrifórnia Morrer", grupo: "Turma da Hora Certa", campea: true },
    { titulo: "Casa Laranja", grupo: "Turma da Hora Certa" },
    { titulo: "Ciranda na Praia", grupo: "Arriba Nóis que o Véio Sumiu" },
    { titulo: "Casinha Pequeninha", grupo: "" },
    { titulo: "Rock Bagual", grupo: "" },
    { titulo: "Filho de Bode Bodinho É", grupo: "Os Besouros" },
  ] },
  { numero: 10, ano: 1991, musicas: [
    { titulo: "Reencontro", grupo: "Luluzinhas", campea: true },
    { titulo: "Viva a Barrifórnia", grupo: "Micuins" },
    { titulo: "Saudosa Maloca", grupo: "Turma da Hora Certa" },
    { titulo: "A Casa do Arrasta Pé", grupo: "Arriba Véio" },
    { titulo: "Donas", grupo: "Os Besouros" },
    { titulo: "Lembranças do Opapa", grupo: "Micuins" },
  ] },
  { numero: 11, ano: 1992, musicas: [
    { titulo: "Turma dos Pescadores", grupo: "Preta de Pixe e os 7 Anões" },
    { titulo: "Tempo Perdido", grupo: "The Alliens" },
    { titulo: "Rock do Fogão", grupo: "Arriba nóis que o véio sumiu, A Renata fugiu, levou o Raul junto e quem não participa fica com cara de bundão" },
    { titulo: "A Bruxa de Férias", grupo: "A Bruxa de Férias" },
    { titulo: "Descendentes", grupo: "Micuins" },
    { titulo: "O Guardião das Fêmeas", grupo: "Arriba nóis que o véio sumiu, A Renata fugiu, levou o Raul junto e quem não participa fica com cara de bundão", campea: true },
  ] },
  { numero: 12, ano: 1993, musicas: [
    { titulo: "Esse ano", grupo: "" },
    { titulo: "Unidos para Sempre", grupo: "Turma da Hora Certa", campea: true },
    { titulo: "Rock do pestinha", grupo: "" },
    { titulo: "O novo galo da praia", grupo: "" },
    { titulo: "Babacão Besta", grupo: "" },
    { titulo: "Debaixo dos caracóis dos seus cabelos", grupo: "" },
    { titulo: "Festas de Aniversário", grupo: "Turma da Hora Certa" },
    { titulo: "Quem Sumiu com a Bolinha", grupo: "Preta de Pixe e os 7 Anões" },
    { titulo: "Mania de Guri", grupo: "" },
    { titulo: "Tetas negras", grupo: "" },
    { titulo: "Canto Barropretense", grupo: "Os Afrobiônicos" },
    { titulo: "O luar", grupo: "" },
    { titulo: "Xote da Bisa", grupo: "Arriba Nós que o Véio Sumiu a Renata Voltou e o Beló Pediu Emprestado e Não Devolveu" },
    { titulo: "Ida à Oásis", grupo: "Seven Girls" },
    { titulo: "Força Flor", grupo: "" },
    { titulo: "Oh!", grupo: "" },
    { titulo: "Veraneio da Rosiméri", grupo: "" },
    { titulo: "Te ... Maninha", grupo: "" },
    { titulo: "Bota rolha", grupo: "" },
    { titulo: "Os gatões", grupo: "" },
    { titulo: "Vocação", grupo: "" },
    { titulo: "Terror das Primas", grupo: "" },
    { titulo: "Nós em PoA", grupo: "" },
    { titulo: ".. A Odisséia", grupo: "" },
  ] },
  { numero: 13, ano: 1994, musicas: [
    { titulo: "A Vida Continua", grupo: "Os Injustiçados" },
    { titulo: "Drama Canino em 2 atos", grupo: "Abóboras Asmáticas" },
    { titulo: "A Nau do Capitão", grupo: "Os Marujos" },
    { titulo: "Amigos", grupo: "Cupins" },
    { titulo: "Bandonese", grupo: "Turma do Martini" },
    { titulo: "Ele Tá Acabado", grupo: "Mocidade Dependente" },
    { titulo: "Quinzena do Pototo", grupo: "Abóboras Sedentas" },
    { titulo: "A Duna", grupo: "Preta de Piche e os 7 Anões" },
    { titulo: "Paguei e Não Recebi", grupo: "Masturbanda" },
    { titulo: "Azares da Vida", grupo: "Overdose" },
    { titulo: "J / Barro Preto", grupo: "Los Cucarachas" },
    { titulo: "Toda Vez que eu Chego na Praia", grupo: "Mocidade Dependente" },
    { titulo: "Buchincho no Campinho", grupo: "Afrobiônicos" },
    { titulo: "Ram Tcham Tcham", grupo: "Abóboras Estúpidas" },
    { titulo: "Recuerdos dos 18", grupo: "Overdose", campea: true },
    { titulo: "O Astrólogo", grupo: "Mocidade Dependente" },
    { titulo: "Sapeca", grupo: "Overdose" },
    { titulo: "Praia Bonita", grupo: "Los Cucarachas" },
    { titulo: "Pototo o Ex-animal", grupo: "Verdão" },
    { titulo: "Roque do Pom-Pom", grupo: "Overdose" },
    { titulo: "O Direito de Amar", grupo: "As Viúvas do Punhobol" },
    { titulo: "Chico 5, A Epopéia", grupo: "Beers for Beers" },
    { titulo: "News Paper", grupo: "Overdose" },
    { titulo: "Ondinha", grupo: "Abóboras Sangrentas" },
    { titulo: "Moça na Sampa", grupo: "Los Cucarachas" },
    { titulo: "Chico 6, A Chinelagem", grupo: "Mocidade Dependente" },
    { titulo: "Contagem", grupo: "Overdose" },
    { titulo: "A Volta do Praga", grupo: "Afrobiônicos" },
    { titulo: "Turma do Martini", grupo: "Turma do Martini" },
    { titulo: "Hino à Barrifórnia", grupo: "Los Cucarachas" },
    { titulo: "Macumba", grupo: "Abóboras Selvagens" },
    { titulo: "O Matador", grupo: "Mocidade Dependente" },
    { titulo: "Herança", grupo: "Overdose" },
    { titulo: "Cerveja de Canequinha", grupo: "Abóboras Silvestres" },
    { titulo: "Jurassic Park", grupo: "Mocidade Dependente" },
    { titulo: "A Saga de Kevin", grupo: "Turma do Martini" },
    { titulo: "Que Bom .... Veranear", grupo: "Os Otimistas" },
  ] },
  { numero: 14, ano: 1995, musicas: [
    { titulo: "Tres Automobiles", grupo: "" },
    { titulo: "A Milonga do Bagaço", grupo: "Pedras Rolantes" },
    { titulo: "O sonho", grupo: "" },
    { titulo: "Nós vamos invadir sua praia", grupo: "" },
    { titulo: "Para honrar a camiseta", grupo: "" },
    { titulo: "Praia de aventura", grupo: "" },
    { titulo: "Vou te contar", grupo: "" },
    { titulo: "A um passo da eternidade", grupo: "" },
    { titulo: "Sasso se irritando", grupo: "" },
    { titulo: "Pezinho", grupo: "Filhos Amados" },
    { titulo: "Dente outra vez", grupo: "" },
    { titulo: "Meus filhos", grupo: "" },
    { titulo: "Cade o Assunto", grupo: "Casa da Sogra" },
    { titulo: "Gloria, Aleluia", grupo: "Arriba Nóis que Sobramos" },
    { titulo: "Pobre moço", grupo: "" },
    { titulo: "[Cupins]", grupo: "" },
    { titulo: "O Bode Cor de Rosa", grupo: "Turma do Martini", campea: true },
    { titulo: "De micuim pra micróbio", grupo: "" },
    { titulo: "Pequena homenagem a prima carioca envolvida em atentado ao pudor nas brancas areias das praias de águas límpidas do litoral gaucho", grupo: "" },
    { titulo: "Casa da Sogra", grupo: "Casa da Sogra" },
    { titulo: "Chamando o Hugo", grupo: "Pedras Rolantes" },
    { titulo: "Cai cai Goleira", grupo: "" },
    { titulo: "O paraiso", grupo: "" },
    { titulo: "Cavalo dado Nao se olha os dentes", grupo: "" },
    { titulo: "Homenagem ao Nando", grupo: "" },
    { titulo: "Homenagem ao Pototo", grupo: "" },
    { titulo: "Socorro na praia", grupo: "" },
  ] },
  { numero: 15, ano: 1996, musicas: [
    { titulo: "O Milagre", grupo: "" },
    { titulo: "Família Animal", grupo: "" },
    { titulo: "E Eles", grupo: "" },
    { titulo: "veraneio é bom", grupo: "" },
    { titulo: "A casa da Tia Heca", grupo: "" },
    { titulo: "Só pra te enganar", grupo: "" },
    { titulo: "Sonhos de Verão", grupo: "" },
    { titulo: "Babel", grupo: "" },
    { titulo: "Bad boy", grupo: "" },
    { titulo: "Chile Lindo", grupo: "Arriba Véio", campea: true },
    { titulo: "A Saga de Floripa", grupo: "Mandacevas" },
    { titulo: "E elas entram em campo", grupo: "" },
    { titulo: "Xuri again", grupo: "" },
    { titulo: "Circo de Punhobolins", grupo: "" },
    { titulo: "O amor é lindo, o amor é belo", grupo: "" },
    { titulo: "Amessão", grupo: "" },
    { titulo: "Tetas", grupo: "" },
    { titulo: "A luz no fim do túnel", grupo: "" },
  ] },
  { numero: 16, ano: 1997, musicas: [
    { titulo: "Confusão", grupo: "" },
    { titulo: "Se meu Emprego Faillace", grupo: "Ratos de Laboratório", campea: true },
    { titulo: "Davi e Golias", grupo: "Turma do Martini" },
    { titulo: "Tô Cansado", grupo: "Turma do Martini" },
    { titulo: "Todos Juntos", grupo: "Todos Juntos", campea: true },
  ] },
  { numero: 17, ano: 1998, musicas: [
    { titulo: "O Doutor", grupo: "Grupo Nós" },
    { titulo: "Ó Como Dói", grupo: "Turma da Última Hora" },
    { titulo: "Rima em Ado, sem Viado", grupo: "Grupo Nós" },
    { titulo: "Vir no Feriado", grupo: "Grupo Nós" },
    { titulo: "Pedrão", grupo: "Família Sol, Lá, Si" },
    { titulo: "Estranho Amori", grupo: "Mandacevas" },
    { titulo: "Era uma Vez", grupo: "Pais e Filhos" },
    { titulo: "O Salva Vidas", grupo: "Grupo Nós" },
    { titulo: "Humilhação (ou o milho em ação) (ou ainda Carolina de Jesus)", grupo: "Mandacevas" },
    { titulo: "O Novo Clubão", grupo: "Afrobiônicos" },
    { titulo: "Melô do Centão", grupo: "Ratos de Laboratório" },
    { titulo: "Cantando com Alegria", grupo: "Arriba Véio" },
    { titulo: "O Bom Paizão", grupo: "Os Bons Paizão" },
    { titulo: "O Perú", grupo: "Turma do Sobrado" },
    { titulo: "Coisa de Maluco", grupo: "Grupo Nós" },
    { titulo: "Festa da Música Familiér", grupo: "Ratos de Laboratório", campea: true },
    { titulo: "Fumando Espero a Cinza Cair", grupo: "Arriba Véio" },
    { titulo: "Canção de Protesto na Praia II", grupo: "Afrobiônicos" },
    { titulo: "Nós Tardamus com as Previsões de 1998", grupo: "Grupo Nós" },
    { titulo: "Mamíferos da Serramalte", grupo: "Mandacevas" },
  ] },
  { numero: 18, ano: 1999, musicas: [
    { titulo: "Cinco de Coração", grupo: "" },
    { titulo: "As Gêmeas", grupo: "" },
    { titulo: "Ich", grupo: "Mandacevas" },
    { titulo: "Minas Gerais", grupo: "Extrema Unção" },
    { titulo: "A Vida Vista pelo Misterix", grupo: "Casa Verde" },
    { titulo: "Titanic", grupo: "Barriga Véio" },
    { titulo: "Estava o Fidel no Seu Lugar", grupo: "Mandacevas" },
    { titulo: "A Epopéia Barropretense", grupo: "Nós Dois" },
    { titulo: "Tu És", grupo: "Mandacevas" },
    { titulo: "Veraneio Poliglota", grupo: "Extrema Unção" },
    { titulo: "O Dia Está Tão Lindo", grupo: "As Gêmeas" },
    { titulo: "Fiquei Sabendo", grupo: "Mandacevas" },
    { titulo: "Miss Brasil 2000", grupo: "Extrema Unção" },
    { titulo: "Pout Pourri do Café", grupo: "Barriga Véio" },
    { titulo: "A Hora do Lanchinho", grupo: "As Gêmeas" },
    { titulo: "Eu e Meus Cachinhos", grupo: "O Grupo do Sobrado" },
    { titulo: "O Tchan na Alemanha", grupo: "Barriga Véio" },
    { titulo: "O Sugismundo", grupo: "Extrema Unção" },
    { titulo: "Baliza", grupo: "Girafa e Coelho" },
    { titulo: "A Despedida", grupo: "Ratos de Laboratório" },
    { titulo: "Adereços e Alegorias", grupo: "Casa Verde" },
    { titulo: "Chup-Chup de Butiá", grupo: "Mandacevas", campea: true },
    { titulo: "Tio Jorge Tinha Razão", grupo: "Ratos de Laboratório" },
    { titulo: "Rua...", grupo: "Mandacevas" },
  ] },
  { numero: 19, ano: 2000, musicas: [
    { titulo: "Diário", grupo: "Nós Achamos", campea: true },
    { titulo: "Garça", grupo: "Mandacevas" },
    { titulo: "Murcilia", grupo: "Mandacevas" },
    { titulo: "Strawberries fiz teus Forévis", grupo: "Mandacevas" },
  ] },
  { numero: 20, ano: 2001, musicas: [
    { titulo: "Por Vocês", grupo: "As Primas Superpoderosas" },
    { titulo: "Háááá, Heim, Dani?!", grupo: "Lampião e Maria Bonita" },
    { titulo: "Tributo ao Ônibus", grupo: "Viajantes das Dunas" },
    { titulo: "Não sou mais Perú", grupo: "Arriba Moço" },
    { titulo: "O Ônibus", grupo: "Afrobiônicos" },
    { titulo: "O Cuco", grupo: "Quarteto em Si e o Dó Maior" },
    { titulo: "Velhos Velhacos", grupo: "Mandacevas" },
    { titulo: "A Promessa", grupo: "Quarteto em Si e o Dó Maior" },
    { titulo: "Lulus Ano 2000", grupo: "Luluzinhas" },
    { titulo: "Conversas Marias", grupo: "Arriba Moço" },
    { titulo: "Venho Aqui", grupo: "Os Otimistas" },
    { titulo: "Eu Quero Voltar para a Praia", grupo: "Os Hansos" },
    { titulo: "Laços de Família", grupo: "Quarteto em Si e o Dó Maior" },
    { titulo: "Vou ter que Esperar", grupo: "Spice Cousins" },
    { titulo: "Barro Preto Edi Mais", grupo: "Arriba Moço", campea: true },
    { titulo: "E o Boris (unplugged)", grupo: "Mandacevas" },
    { titulo: "Garotas da Família", grupo: "Os Hansos" },
    { titulo: "No Stress", grupo: "Spice Cousins" },
    { titulo: "Como é Bom Tá Aqui Agora", grupo: "O Dani foi prá Imbé, a Joana pegou piolho com o Bruno em Mostardas, meus primos tão trabalhando e só fiquei eu e as tias" },
    { titulo: "Os Primos", grupo: "As Primas Superpoderosas" },
    { titulo: "Robauglud", grupo: "Dois Meninos de Ouro" },
    { titulo: "Garotos da Família - A Revanche", grupo: "Spice Cousins" },
    { titulo: "Banho de Mar", grupo: "As Primas Superpoderosas" },
    { titulo: "Hino Marcial dos Mandacevas", grupo: "Mandacevas" },
    { titulo: "Praia Cheia", grupo: "Quarteto em Si e o Dó Maior" },
    { titulo: "Mamãe Fresca", grupo: "Arriba Moço" },
    { titulo: "Diversão", grupo: "Mandacevas" },
    { titulo: "Reflexões erótico-sentimentais do Matias, o multi-homem com movimento sexy", grupo: "Forró do Bó" },
    { titulo: "Cocozeira do Fufi", grupo: "Mandacevas" },
    { titulo: "Fevereiro 2001", grupo: "Afrobiônicos" },
    { titulo: "Embromação", grupo: "Os Embromaprimos" },
  ] },
  { numero: 21, ano: 2002, musicas: [
    { titulo: "Janeiro em Barro Preto foi Legal", grupo: "Sobrado Misto", campea: true },
    { titulo: "Aleluia", grupo: "Mandacevas" },
    { titulo: "Hino dos Mandacevas II", grupo: "Mandacevas" },
  ] },
  { numero: 22, ano: 2003, musicas: [
    { titulo: "Vou esperar", grupo: "" },
    { titulo: "Os Pares", grupo: "Mandacevas" },
    { titulo: "Isso", grupo: "" },
    { titulo: "Minha praia", grupo: "" },
    { titulo: "Apelo do desesperado", grupo: "" },
    { titulo: "Dura realidade", grupo: "Mandacevas" },
    { titulo: "Algo assim", grupo: "" },
    { titulo: "O Parque da Adrenalina", grupo: "" },
    { titulo: "O Céu é o Limite", grupo: "Peter Pan e o Pé de Feijão", campea: true },
    { titulo: "5 priminhas", grupo: "" },
    { titulo: "Éaidádi", grupo: "" },
    { titulo: "Não Insistam com o Flávio", grupo: "Mandacevas Ortodoxos" },
    { titulo: "Super Raul", grupo: "" },
    { titulo: "Não tão com nada", grupo: "" },
    { titulo: "Dança dos Primos", grupo: "" },
    { titulo: "Todas as Barrifórnias", grupo: "" },
    { titulo: "Poutpourry Barropretense", grupo: "" },
    { titulo: "Mamandocevas", grupo: "Mandacevas" },
    { titulo: "Barro Preto é demais", grupo: "" },
    { titulo: "O Jardim Atlântico", grupo: "" },
    { titulo: "Vai, Vai, Vai", grupo: "E.E.U.U" },
    { titulo: "Acústico", grupo: "" },
    { titulo: "Tributo ao Flávio", grupo: "" },
    { titulo: "Que Estay Pensando", grupo: "Mandacevas" },
    { titulo: "É Devagar", grupo: "Só Nói" },
    { titulo: "Nosso Verão", grupo: "Maluketes" },
    { titulo: "Maria", grupo: "quem vai ficar com Mary?" },
    { titulo: "Vovó eu quero", grupo: "" },
    { titulo: "Verão diferente", grupo: "" },
    { titulo: "Hansi, a Vovozinha", grupo: "Mandacevas" },
    { titulo: "Aconteceu", grupo: "" },
    { titulo: "Não se deve faltar", grupo: "" },
  ] },
  { numero: 23, ano: 2004, musicas: [
    { titulo: "Suspeito", grupo: "Primatas", campea: true },
  ] },
  { numero: 24, ano: 2005, musicas: [
    { titulo: "Ser Feliz", grupo: "Ihvi", campea: true },
    { titulo: "Suspeito", grupo: "As Priminhas" },
    { titulo: "O Tal Esporão", grupo: "" },
    { titulo: "Domingo", grupo: "Mandacevas" },
    { titulo: "Pototo", grupo: "Mandacevas" },
    { titulo: "Helmut", grupo: "Mandacevas" },
    { titulo: "Gira", grupo: "Der Kleine Mandacevas" },
    { titulo: "As Peripécias do Último Mandaceva Solteiro", grupo: "Mandacevas" },
  ] },
  { numero: 25, ano: 2006, musicas: [
    { titulo: "Ui ui ui", grupo: "" },
    { titulo: "Jubileu", grupo: "Mandacevas" },
    { titulo: "A Girafa", grupo: "" },
    { titulo: "Vou pra Praia Sim", grupo: "" },
    { titulo: "A praia que eu gosto", grupo: "" },
    { titulo: "O tesouro", grupo: "" },
    { titulo: "Lá em Barro Preto", grupo: "" },
    { titulo: "Barro Preto é a sensação", grupo: "" },
    { titulo: "Praia com Sol", grupo: "" },
    { titulo: "Velha branca", grupo: "" },
    { titulo: "O Professor", grupo: "Mandacevas" },
    { titulo: "Mais uma vez", grupo: "" },
    { titulo: "Ópera do Alejandro", grupo: "" },
    { titulo: "Quero-quero", grupo: "" },
    { titulo: "A sua canção", grupo: "" },
    { titulo: "Moicano", grupo: "" },
    { titulo: "2000", grupo: "" },
    { titulo: "Renasci há 10 anos atrás", grupo: "Mandacevas", campea: true },
    { titulo: "Feliz em só ser", grupo: "" },
    { titulo: "Os brodi do Álvaro", grupo: "Homenagem aos amigos Lucas, Gui e Fabio" },
    { titulo: "Escravas da vó", grupo: "" },
    { titulo: "Bibidi bebede Bru", grupo: "" },
    { titulo: "Bailarina", grupo: "" },
    { titulo: "Sabine’s Histories", grupo: "" },
    { titulo: "Xi", grupo: "" },
    { titulo: "Quero-quero parte 2 - Uma odisseia", grupo: "" },
    { titulo: "Hahu de nada", grupo: "Mandacevas" },
    { titulo: "Do lado de Eden", grupo: "" },
    { titulo: "O Bruda no paraiso", grupo: "" },
    { titulo: "Fui à praia", grupo: "" },
    { titulo: "Nada de sorvete", grupo: "" },
    { titulo: "Semana em Barro Preto", grupo: "" },
    { titulo: "Eram garotos que como nós", grupo: "" },
    { titulo: "Leve a tenda", grupo: "" },
    { titulo: "Mare Nostrum", grupo: "" },
    { titulo: "Morgen Kommt der Opa Schorch", grupo: "Mandacevas" },
    { titulo: "Tá Tá Tá", grupo: "" },
    { titulo: "E lá vou eu", grupo: "" },
  ] },
  { numero: 26, ano: 2007, musicas: [
    { titulo: "Perús de Carro", grupo: "Patota do Pototo" },
    { titulo: "O Que o Opa Tem", grupo: "Carol e Sabine" },
    { titulo: "O Canto dos Cisnes", grupo: "Casaleirinho" },
    { titulo: "Meus Verões à Beira-Mar", grupo: "Grupo Eu" },
    { titulo: "El Duelo", grupo: "Os Expressivos" },
    { titulo: "Até Kaiser Eu To Tomando", grupo: "Mandacevas" },
    { titulo: "Saco Cheio", grupo: "Patota da Tia Heca" },
    { titulo: "Melô do Sorvete", grupo: "Os Casquinhas" },
    { titulo: "???", grupo: "Carol, Sabine, ..." },
    { titulo: "?? Não Quero Mais Ser Quero-Quero", grupo: "Quero-Queros" },
    { titulo: "????", grupo: "Kitty e???" },
    { titulo: "???", grupo: "???" },
    { titulo: "Quero-quero mas nem tanto", grupo: "Mandacevas", campea: true },
    { titulo: "??? vou te contar meus olhos já não podem ver", grupo: "???" },
    { titulo: "?? ritual de acasalamento", grupo: "Quero-Queros" },
    { titulo: "?? acordai", grupo: "???" },
    { titulo: "Era Uma Vez", grupo: "Spice Cousins" },
    { titulo: "?? Mateus..", grupo: "???" },
    { titulo: "?? Barro Preto", grupo: "??" },
    { titulo: "?? Não sei tocar nada assim", grupo: "Roberto" },
  ] },
  { numero: 27, ano: 2008, musicas: [
    { titulo: "Síndrome do Ninho Vazio", grupo: "Tia Heca", campea: true },
    { titulo: "Saudades do Centão", grupo: "Mandacevas" },
    { titulo: "Chamila", grupo: "Mandacevas Ativos" },
    { titulo: "Por Você", grupo: "Mandacevas Ativos" },
    { titulo: "Trova", grupo: "QueroCevas" },
    { titulo: "Bochincho de Cobra", grupo: "Táta" },
  ] },
  { numero: 28, ano: 2009, musicas: [
    { titulo: "Beijinho doce", grupo: "Se Lambusa" },
    { titulo: "Assassinato do Ingles", grupo: "The Sisters" },
    { titulo: "Seleção Natural", grupo: "Mandacevas" },
    { titulo: "Lilica ou Mix", grupo: "Hamstres" },
    { titulo: "Inundação", grupo: "Quem Sobrou" },
    { titulo: "A Praia", grupo: "Pink, White, Red" },
    { titulo: "Bruda, tu Sempre Serás Campeão", grupo: "Quero-Queros", campea: true },
    { titulo: "Tio Maravilha", grupo: "Mandacevas" },
    { titulo: "A Mudança", grupo: "Ex-Chilenos" },
    { titulo: "Heroica Confraria", grupo: "Identidade Secreta" },
    { titulo: "Força do Remo", grupo: "Quem Sobrou" },
    { titulo: "A Nossa Bisa", grupo: "Os Bisnetos" },
    { titulo: "Trem da Alegria", grupo: "Mandacevas" },
    { titulo: "Confissões", grupo: "Ex-chilenos" },
    { titulo: "Para ser Feliz", grupo: "Pink, White, Red" },
    { titulo: "Oração aos Quero-Queros", grupo: "Quero-Queros" },
    { titulo: "Sem Vocês", grupo: "Quem Sobrou" },
    { titulo: "Minha Filhinha [ou Gabi]", grupo: "The Sister" },
    { titulo: "Concha y Toro", grupo: "Mandacevas" },
    { titulo: "Sempre Lembrando", grupo: "Ex-Chilenos" },
    { titulo: "Pra Voltar a Sonhar", grupo: "Representação da Patota do Pototo" },
    { titulo: "Hino aos Mandacevas Revisado", grupo: "Quero-Queros" },
    { titulo: "Doutora de Família", grupo: "Quem Sobrou" },
    { titulo: "M.C.", grupo: "Quero-Queros" },
  ] },
  { numero: 29, ano: 2010, musicas: [
    { titulo: "A Roda do Chimarrão", grupo: "Maria e Flavio", campea: true },
    { titulo: "Hotten Toten", grupo: "Mandacevas" },
    { titulo: "Pagode do Maneco", grupo: "Mandacevas" },
    { titulo: "A Revoada da Cegonha", grupo: "Mandacevas" },
  ] },
  { numero: 30, ano: 2011, musicas: [
    { titulo: "Endereço", grupo: "Vacas" },
    { titulo: "Tchu-Tchu-rurururu", grupo: "As Roqueiras" },
    { titulo: "Férias", grupo: "GLB" },
    { titulo: "A Corrida", grupo: "GaBeto" },
    { titulo: "A Praia", grupo: "Os Corujas" },
    { titulo: "Será que ele é?", grupo: "Os Expressivos" },
    { titulo: "Oma Helga", grupo: "Os Chatos do Churrasco" },
    { titulo: "As Lendas de Barro Preto", grupo: "Os Caçadores de Aventuras", campea: true },
    { titulo: "Alegrete em Janeiro", grupo: "Laura" },
    { titulo: "Vigitec", grupo: "Mandacevas" },
    { titulo: "Barro Preto", grupo: "Os Corujas" },
    { titulo: "Ilarilarimu", grupo: "VACAS" },
    { titulo: "Pega o Bruno", grupo: "Pega pra Capar" },
    { titulo: "No Marina Park", grupo: "GLB" },
    { titulo: "Beló Nosso Amigo", grupo: "The Crocs" },
    { titulo: "Faixa de Capitão", grupo: "Ratos de Laboratório" },
    { titulo: "A Volta do Braço", grupo: "Mandacevas", campea: true },
    { titulo: "Mami", grupo: "A Casa da Bella" },
    { titulo: "Já Ganhou", grupo: "Os Humildes" },
    { titulo: "One", grupo: "Sopa" },
    { titulo: "Immer Jung", grupo: "Mandacevas" },
    { titulo: "Gavião", grupo: "Die Feistauer's" },
    { titulo: "Bisa é Demais (Anita e os Rabos de Palha) ou Algo Mudou ou Tudo Mudou", grupo: "" },
    { titulo: "Quero-Quero Repórter", grupo: "Os Expressivos" },
    { titulo: "Procuro Uma Praia", grupo: "A Casa das Sapas" },
    { titulo: "O Último dos Sem Canos", grupo: "Mandacevas" },
    { titulo: "O Convite do Carlitos", grupo: "A Casa das Sapas" },
  ] },
  { numero: 31, ano: 2012, musicas: [
    { titulo: "A Barrifórnia", grupo: "GiBiDu" },
    { titulo: "Oi Gabriel", grupo: "WX" },
    { titulo: "Vizinhas", grupo: "Pipocas" },
    { titulo: "O Mês Ideal", grupo: "VACAS" },
    { titulo: "Bruno Incrível", grupo: "Quero-Queros" },
    { titulo: "O Drama dos Pequenos", grupo: "X" },
    { titulo: "Hino do Opa", grupo: "Sacripantas" },
    { titulo: "Réquiem", grupo: "Mandacevas" },
    { titulo: "Tradição de Mandacevas", grupo: "Arriba Véio" },
    { titulo: "Estava o Tio Jorge em seu lugar", grupo: "Quero-Queros", campea: true },
    { titulo: "Nossa Praia", grupo: "VACAS" },
    { titulo: "Bruda 40", grupo: "X" },
    { titulo: "Campo Minado", grupo: "Flavinço e Roseta Maria" },
    { titulo: "Férias", grupo: "Os Caçadores de Aventuras" },
    { titulo: "TJ, Superstar", grupo: "Mandacevas" },
    { titulo: "Miguel", grupo: "Opatoto" },
    { titulo: "A Gente Faz pra Você", grupo: "Arriba Véio" },
    { titulo: "Aproveitou", grupo: "X" },
    { titulo: "Hey Brude", grupo: "Quero-Queros" },
    { titulo: "As Vacas", grupo: "5 Priminhas" },
    { titulo: "O Camarote", grupo: "MC Brudão" },
    { titulo: "Aula de Vioooolão", grupo: "Flavox" },
    { titulo: "Kleiner Peter", grupo: "X" },
    { titulo: "Eu sem Você", grupo: "Luluzinhas sem Lulu" },
    { titulo: "Campinho Encharcadinho do Jorjão", grupo: "Quero-Queros" },
    { titulo: "Uma Odisséia Bambástica", grupo: "Mandacevas" },
  ] },
  { numero: 32, ano: 2013, musicas: [
    { titulo: "Lembram Moços/Dona do Campinho", grupo: "O Vendedor", campea: true },
    { titulo: "Agora Sim", grupo: "Mandacevas" },
    { titulo: "Eu quero tá Mamado", grupo: "Mandacevas" },
    { titulo: "Hansi, o Guri de Uruguaiana", grupo: "Mandacevas" },
    { titulo: "O Poste", grupo: "Mandacevas" },
    { titulo: "She is Teenager", grupo: "Mandacevas" },
    { titulo: "Aventuras que não tem Idade", grupo: "Os Caçadores de Aventuras" },
  ] },
  { numero: 33, ano: 2014, musicas: [
    { titulo: "Barro Preto Sede para 2014", grupo: "Mandacevas", campea: true },
    { titulo: "A Busca do Décimo Homem", grupo: "Mandacevas" },
    { titulo: "Ê ô ê ô", grupo: "Mandacevas" },
    { titulo: "Eu me amarrei", grupo: "Mandacevas" },
    { titulo: "Gui Brabo", grupo: "Mandacevas" },
    { titulo: "De Olho na Taça", grupo: "Ratos de Laboratório" },
  ] },
  { numero: 34, ano: 2015, musicas: [
    { titulo: "Dá pra adaptar??", grupo: "União Estável", campea: true },
    { titulo: "Portabilidade", grupo: "Luluzinhas Turbinadas" },
    { titulo: "Te Cuida Índio Velox", grupo: "Luluzinhas Turbinadas" },
    { titulo: "A Oma é Demais", grupo: "Pototo" },
    { titulo: "Imagina", grupo: "Pototo" },
    { titulo: "Não te Troco Meu Barro Preto", grupo: "Paula - Alvin e os Esquilos" },
    { titulo: "Lá Vem a Paula", grupo: "Paula - Alvin e os Esquilos" },
    { titulo: "Poutporri", grupo: "As Mães D'aguas" },
    { titulo: "Combinação", grupo: "As Mães D'aguas" },
    { titulo: "Herdeiros do Barro Preto", grupo: "Camundongos de Laboratório" },
    { titulo: "Donga", grupo: "Mandacevas" },
    { titulo: "Flávio e Maria", grupo: "Mandacevas" },
    { titulo: "Maçarico no Fubá", grupo: "Mandacevas" },
    { titulo: "O Aviador", grupo: "Mandacevas", campea: true },
    { titulo: "Os Bala", grupo: "Mandacevas" },
  ] },
  { numero: 35, ano: 2016, musicas: [
    { titulo: "Celebrando a Vida", grupo: "Tetas Negras", campea: true },
    { titulo: "Mamãe Sarada", grupo: "Mandacevas" },
    { titulo: "Não deixe os Mandacevas morrer", grupo: "Mandacevas" },
    { titulo: "Top Five", grupo: "Top Five" },
  ] },
  { numero: 36, ano: 2017, musicas: [
    { titulo: "Não vale bomba", grupo: "Quero-Queros", campea: true },
    { titulo: "Veraneio da Maria Flor", grupo: "" },
    { titulo: "Alforria", grupo: "Mandacevas" },
    { titulo: "Dois patinhos lá na boa", grupo: "Mandacevas" },
    { titulo: "Super Heca 2", grupo: "Mandacevas" },
    { titulo: "O rabo da Oma Heca", grupo: "crianças do sobrado" },
    { titulo: "Banguela", grupo: "Naneca" },
    { titulo: "Barro Preto é a minha praia", grupo: "Luluzinhas" },
    { titulo: "Passa Passará", grupo: "Luluzinhas" },
  ] },
  { numero: 37, ano: 2018, musicas: [
    { titulo: "Vocês ao meu Redor", grupo: "Paula", campea: true },
    { titulo: "A Gabi quer ser Mandacevas", grupo: "Mandacevas" },
  ] },
  { numero: 38, ano: 2019, musicas: [
    { titulo: "Pula Pula", grupo: "Bichinho da Praia" },
    { titulo: "TIM", grupo: "Cancioneros" },
    { titulo: "Priminhos Legais", grupo: "" },
    { titulo: "Os Primos", grupo: "Mirabolantes" },
    { titulo: "Você Quer Brincar na Praia?", grupo: "Os Cariocas" },
    { titulo: "Levanta", grupo: "Mirabolantes" },
    { titulo: "Dominique", grupo: "As Cachorrentas" },
    { titulo: "Brincar na Praia", grupo: "Mirabolantes", campea: true },
    { titulo: "Positividade", grupo: "Havaianas" },
    { titulo: "Cápsula do Tempo", grupo: "Mandacevas" },
    { titulo: "Luluzinhas", grupo: "Luluzinhas" },
    { titulo: "Südamerikanischer Wasserrad-Fahr-Verein", grupo: "Carolinas" },
    { titulo: "Dô e Domi", grupo: "As Cachorrentas" },
    { titulo: "Barro Preto é a Razão", grupo: "Amonstros SA" },
    { titulo: "A Nau para César", grupo: "Mandacevas" },
    { titulo: "O Mapa", grupo: "Luluzinhas", campea: true },
    { titulo: "Tesouros", grupo: "Camilla" },
    { titulo: "Com Poquita Coisa", grupo: "Patota da Tia Heca" },
    { titulo: "Moma Mia", grupo: "Mandacevas" },
    { titulo: "Humuhumunukunukuapua-a", grupo: "As Havaianas" },
    { titulo: "Volta Maria", grupo: "Volta Maria" },
    { titulo: "Baniaxé", grupo: "Cacaleco" },
    { titulo: "Fé no Nando", grupo: "Mandacevas" },
  ] },
  { numero: 39, ano: 2020, musicas: [
    { titulo: "A Graça do Nosso Verão", grupo: "Mirabolantes" },
    { titulo: "Casinha na Praia", grupo: "Os Cariocas" },
    { titulo: "Uma Coisa que Sempre Quis", grupo: "Henrique" },
    { titulo: "Bela Cachorrinha", grupo: "Praia" },
    { titulo: "Feliz na Praia", grupo: "Os Três Mosqueteiros" },
    { titulo: "Para a Praia Eu Vou", grupo: "Os Marujos" },
    { titulo: "A Baleia", grupo: "As Baleirinas" },
    { titulo: "Jogos da Meia-Noite", grupo: "Nós Três" },
    { titulo: "Praiados", grupo: "Praiados" },
    { titulo: "Pra Lá do Muro", grupo: "Perrengue e Coloridos" },
    { titulo: "Funcional", grupo: "As Dom Docas" },
    { titulo: "Abandono de Incapaz", grupo: "Helgalinha" },
    { titulo: "Fantasma da Ópera", grupo: "Apresentação Especial" },
    { titulo: "Cinquentenário", grupo: "Os Bissextos" },
    { titulo: "Prometi", grupo: "Spice Cousins" },
    { titulo: "Touro Andino", grupo: "Mandacevas" },
    { titulo: "O Barrigudo", grupo: "Arriba Véio" },
    { titulo: "Deu Pra Ti", grupo: "Moranquinhos" },
    { titulo: "Um Pedaço de Mim", grupo: "Pedaço dos Bissextos" },
    { titulo: "Veranistas", grupo: "Infectados" },
    { titulo: "Anos de Verão", grupo: "Os Cariocas" },
    { titulo: "Anos", grupo: "Arriba Muito Véio", campea: true },
    { titulo: "O Meu Segredo", grupo: "LudoMike e Dominika" },
    { titulo: "Sonhos de Um Guri", grupo: "Monstros SA" },
    { titulo: "Opa e Oma", grupo: "Luluzinhas" },
    { titulo: "Guria Bem te Quero", grupo: "Ricardo Bissexto" },
    { titulo: "Vou Pra Ti", grupo: "Moranguinhos" },
    { titulo: "O Livro - Conversa com meu Autor", grupo: "Pototo", campea: true },
    { titulo: "Casinho Perdido", grupo: "Caso Perdido" },
    { titulo: "O Dia do Opa", grupo: "Arriba Véio" },
    { titulo: "Pra Tineijar", grupo: "Moranguinhos" },
  ] },
  { numero: 40, ano: 2021, musicas: [
    { titulo: "WhatsApp Beach", grupo: "Banda Papito" },
    { titulo: "Eu tô de férias", grupo: "Primaiada na Praia" },
    { titulo: "Na Praia", grupo: "Sarah" },
    { titulo: "As crianças [parte 1]", grupo: "Praiados" },
    { titulo: "As crianças [parte 2]", grupo: "Praiados" },
    { titulo: "O Coronavirus Maluco", grupo: "Spice Cousins" },
    { titulo: "Superfantástica praia", grupo: "Praiados" },
    { titulo: "Um novo verão", grupo: "Ux Primux" },
    { titulo: "Rotina do Calebe", grupo: "Praiados" },
    { titulo: "L.M.A.A", grupo: "Mandacevas" },
    { titulo: "Nos vamos invadir sua praia", grupo: "Diogo" },
    { titulo: "De longe", grupo: "Luísa, Paula e Marcos" },
    { titulo: "Ninguém aguenta mais essa pandemia", grupo: "Sarah e Ingrid" },
    { titulo: "Barrifornia", grupo: "Bia e seu ukulele" },
    { titulo: "Opa aqui! Opa da!", grupo: "Os marinheiros" },
    { titulo: "Infinita praia", grupo: "Mandacevas" },
    { titulo: "Chatices da praia", grupo: "Os desfraldados" },
    { titulo: "Acampamento", grupo: "Bruno" },
    { titulo: "Inspiração", grupo: "Arriba véia" },
    { titulo: "Pandefornia", grupo: "Lulucevas" },
    { titulo: "A Luz", grupo: "Pototo" },
    { titulo: "O ano precisava de um verão", grupo: "Nóis três", campea: true },
    { titulo: "Em pensamento", grupo: "Luísa" },
    { titulo: "Amon da minha vida", grupo: "Mandacevas", campea: true },
    { titulo: "Criança da Praia", grupo: "Chiquititas" },
    { titulo: "These are The things that we miss Brasil", grupo: "Family Von Trapped" },
    { titulo: "Pedalando para Cidreira", grupo: "Xox" },
    { titulo: "Sol de Barro Preto", grupo: "Laura" },
    { titulo: "Vai demorar", grupo: "Luísa" },
  ] },
  { numero: 41, ano: 2022, musicas: [
    { titulo: "Estrada de Pedra", grupo: "?" },
    { titulo: "Na Praia", grupo: "Ux Primux" },
    { titulo: "Tradições", grupo: "Vitoriosos" },
    { titulo: "Tic-Tac", grupo: "Patota do Pototo" },
    { titulo: "Duas Meninas", grupo: "Patota do Pototo" },
    { titulo: "Velhas e Loucas", grupo: "Luluvéias" },
    { titulo: "O Ano em que a Praia Parou", grupo: "Spice Cousins" },
    { titulo: "Oração à Brian", grupo: "Mandacevas" },
    { titulo: "Com COVID", grupo: "Os Marujos" },
    { titulo: "Carlitros e os Tchuco-tchucos", grupo: "Fiscais do Ibrahma", campea: true },
    { titulo: "Tuco-tuco", grupo: "Tia Heca" },
    { titulo: "A Praia e a Casa", grupo: "Longinios" },
    { titulo: "O Poder da Atração", grupo: "Loginios" },
    { titulo: "Tuco-tuco", grupo: "Admiradores do Tuco-tuco" },
    { titulo: "Arriba (Arriba Nóis) [?]", grupo: "" },
    { titulo: "Dê uma Chance à Barrifórnia da Canção", grupo: "Freddie não Morreu" },
  ] },
  { numero: 42, ano: 2023, musicas: [
    { titulo: "Brincar na Chuva", grupo: "Mirabolantes" },
    { titulo: "Pescaria", grupo: "Mirabolinhos", campea: true },
    { titulo: "De Janeiro e Fevereiro", grupo: "Mirabolantes" },
    { titulo: "Os Olhos de Todo Mundo", grupo: "Mirabolinhos" },
    { titulo: "O Charco", grupo: "Luluzinhas" },
    { titulo: "Seu Carlos", grupo: "Pototo" },
    { titulo: "A Homenagem", grupo: "Arriba Véio" },
    { titulo: "Saudosa Maloca", grupo: "Os Meninos da Floresta" },
    { titulo: "Desfalcados", grupo: "Roqueiros do Roque" },
    { titulo: "Porque Não?", grupo: "Pototo" },
    { titulo: "Das Antigas", grupo: "Luluzinhas" },
    { titulo: "Barrifórnia é Bom Capacete", grupo: "BeTom Jobim", campea: true },
    { titulo: "Quem Bode, Pode", grupo: "Mandacevas" },
    { titulo: "O Último Quero-Quero", grupo: "Quero-Queros" },
    { titulo: "Era Uma Vez", grupo: "Singrid" },
    { titulo: "Vivi com a Vivi", grupo: "Os Penetras" },
  ] },
];

const container = document.querySelector("#lista-edicoes");
const campoBusca = document.querySelector("#busca");
const filtroFavoritos = document.querySelector("#filtro-favoritos");
const contador = document.querySelector("#contador");

function lerFavoritos() {
  const salvo = localStorage.getItem("barrifornia-favoritos");
  return salvo ? JSON.parse(salvo) : [];
}

function salvarFavoritos(lista) {
  localStorage.setItem("barrifornia-favoritos", JSON.stringify(lista));
}

function alternarFavorito(numero) {
  const favoritos = lerFavoritos();
  if (favoritos.includes(numero)) {
    salvarFavoritos(favoritos.filter((item) => item !== numero));
  } else {
    favoritos.push(numero);
    salvarFavoritos(favoritos);
  }
  filtrar();
}

function criarCard(edicao, ehFavorito) {
  const musicas = edicao.musicas
    .map((m) => {
      const grupo = m.grupo ? ` <span class="grupo">— ${m.grupo}</span>` : "";
      const troféu = m.campea ? `<span class="tag-campea" title="Música campeã">🏆</span> ` : "";
      return `<li>${troféu}${m.titulo}${grupo}</li>`;
    })
    .join("");

  const campea = edicao.musicas.find((m) => m.campea);
  const destaque = campea
    ? `<p class="campea-destaque">🏆 Campeã: ${campea.titulo}${campea.grupo ? ` (${campea.grupo})` : ""}</p>`
    : "";

  return `
    <article class="card">
      <div class="card-topo">
        <div>
          <span class="card-ano">${edicao.ano}</span>
          <span class="card-num">${edicao.numero}ª edição</span>
        </div>
        <button
          class="favorito"
          type="button"
          aria-pressed="${ehFavorito}"
          aria-label="Marcar a ${edicao.numero}ª edição como favorita"
          data-numero="${edicao.numero}"
        >★</button>
      </div>
      ${destaque}
      <p class="card-meta">${edicao.musicas.length} músicas registradas</p>
      <ul class="card-musicas">${musicas}</ul>
    </article>
  `;
}

function renderizar(lista) {
  const favoritos = lerFavoritos();

  if (lista.length === 0) {
    container.innerHTML = `<p class="vazio">Nenhuma edição encontrada. Tente outra busca.</p>`;
    contador.textContent = "";
    return;
  }

  const totalMusicas = lista.reduce((soma, e) => soma + e.musicas.length, 0);
  contador.textContent = `${lista.length} edições • ${totalMusicas} músicas`;

  container.innerHTML = lista
    .map((edicao) => criarCard(edicao, favoritos.includes(edicao.numero)))
    .join("");

  document.querySelectorAll(".favorito").forEach((botao) => {
    botao.addEventListener("click", () => {
      alternarFavorito(Number(botao.dataset.numero));
    });
  });
}

function filtrar() {
  const termo = campoBusca.value.toLowerCase().trim();
  const soFavoritos = filtroFavoritos.checked;
  const favoritos = lerFavoritos();

  let resultado = edicoes.filter((edicao) => {
    const musicasTexto = edicao.musicas.map((m) => `${m.titulo} ${m.grupo}`).join(" ");
    const texto = `${edicao.ano} ${edicao.numero} ${musicasTexto}`.toLowerCase();
    return texto.includes(termo);
  });

  if (soFavoritos) {
    resultado = resultado.filter((edicao) => favoritos.includes(edicao.numero));
  }

  renderizar(resultado);
}

campoBusca.addEventListener("input", filtrar);
filtroFavoritos.addEventListener("change", filtrar);
filtrar();
